---

 - name: ensure host name is present in hosts file
   sudo: yes
   lineinfile: dest=/etc/hosts state=present line="{{ vps_ip }} {{ server_name }}"

# Following tasks are commented because certificates are generated directly on target VM
# before deployment (it's a prequisite), we don't need to copy them from deployment VM

# - name: copy certificates
#   sudo: yes
#   copy: src={{ server_name }}.{{ item }} dest={{ main_certs_path }}/{{ item }} owner=root group=root mode=0666
#   with_items:
#     - "{{ server_certificate }}"
#     - "{{ inter_certificate }}"

# - name: copy private key
#   sudo: yes
#   copy: src={{ server_name }}.{{ server_key }} dest={{ main_keys_path }}/{{ server_key }} owner=root group=ssl-cert mode=0640

 - name: ensure apache is installed
   sudo: yes
   apt: name=apache2 update_cache=yes state=present force=yes

 - name: enable apache modules
   sudo: yes
   apache2_module: state=present name={{ item }}
   with_items:
     - proxy
     - proxy_http
     - ldap
     - authnz_ldap
     - ssl
     - rewrite

 - name: ensure modsecurity is installed
   sudo: yes
   apt: name=libapache2-mod-security2 update_cache=yes state=present force=yes

 - name: ensure security.conf is present
   sudo: yes
   copy: src=security.conf dest=/etc/apache2/conf-enabled/ owner=root group=root mode=0640

 - name: ensure boxify files are present
   sudo: yes
   copy: src=Boxify/ dest=/var/www/html/

 - name: ensure boxify main page is present
   sudo: yes
   template: src=index.html.j2 dest=/var/www/html/index.html

 - name: ensure default virtual host is disabled
   sudo: yes
   file: path=/etc/apache2/sites-enabled/000-default.conf state=absent

 - name: enable cache module
   sudo: yes
   file: src=/etc/apache2/mods-available/socache_shmcb.load dest=/etc/apache2/mods-enabled/socache_shmcb.load state=link

 - name: add virtual hosts
   sudo: yes
   template: src={{ item }}.j2 dest=/etc/apache2/sites-available/{{ item }}
   with_items:
     - redirect.conf
     - default.conf

 - name: enable virtual hosts
   sudo: yes
   file: src=/etc/apache2/sites-available/{{ item }} dest=/etc/apache2/sites-enabled/{{ item }} state=link
   with_items:
     - redirect.conf
     - default.conf

 - name: add apache ports
   sudo: yes
   template: src=ports.conf.j2 dest=/etc/apache2/ports.conf

 - name: restart apache
   sudo: yes
   service: name=apache2 state=restarted
